[package]
name = "rust_chat_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc64 = "2.0.0"
tokio = "1.24.1"
